### ISSUE TITLE
Error running 1st test locally

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#16]
I followed the instruction on this page https://www.snaptest.io/doc/getting-started and I am getting an error when running the code generation from the command line.

```
c:\OPT\Tests>git clone https://github.com/ozymandias547/snaptest-harness.git &&
cd snaptest-harness && npm install && snaptest -f **** -r nightwatch -s fla
t -t ******
Cloning into 'snaptest-harness'...
remote: Counting objects: 104, done.
Receiving objectsremote: Total 104 (delta 0), reused 0 (delta 0), pack-reused 10
Receiving objects:  45% (47/104), 17.14 MiB | 2.41 MiB/s
Receiving objects: 100% (104/104), 17.77 MiB | 1.88 MiB/s, done.
Resolving deltas: 100% (50/50), done.
npm WARN snaptest-harness@1.0.0 No repository field.

added 109 packages in 5.888s
'snaptest' is not recognized as an internal or external command,
operable program or batch file.
```

I have npm installed, and ChromeDriver is installed and in the path. The document says to have snaptest-cli installed but no link to show how to install. 

When I run npm test, I get this:
```
c:\OPT\Tests\snaptest-harness>npm test

> snaptest-harness@1.0.0 test c:\OPT\Tests\snaptest-harness
> nightwatch snaptests/tests

There was an error while starting the test runner:

Error: ENOENT: no such file or directory, stat 'c:\OPT\Tests\snaptest-harness\sn
aptests\tests'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.singleSourceFile (c:\OPT\Tests\snaptest-harness\node_modules\night
watch\lib\runner\cli\clirunner.js:193:86)
    at Object.parallelModeWorkers (c:\OPT\Tests\snaptest-harness\node_modules\ni
ghtwatch\lib\runner\cli\clirunner.js:717:44)
    at Object.parseTestSettings (c:\OPT\Tests\snaptest-harness\node_modules\nigh
twatch\lib\runner\cli\clirunner.js:532:14)
    at Object.setup (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch\lib\r
unner\cli\clirunner.js:49:8)
    at Object.exports.runner (c:\OPT\Tests\snaptest-harness\node_modules\nightwa
tch\lib\index.js:551:17)
    at c:\OPT\Tests\snaptest-harness\node_modules\nightwatch\bin\runner.js:10:16

    at Object.exports.cli (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch
\lib\index.js:545:5)
    at Object.<anonymous> (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch
\bin\runner.js:8:14)

npm ERR! Test failed.  See above for more details.
```

System: Windows 7
npm: v5.4.2
ChromeDriver: v2.32 win-32
Node: v6.9.5

As the error says, there is no folder called c:\OPT\Tests\snaptest-harness\sn
aptests in the structure generated. Did I miss a step somewhere?

**Comment by ozymandias547** [comment]
Yea, this part can be tricky - that error is basically stating that no tests were generated.   The doc on [https://www.snaptest.io/doc/overview](https://www.snaptest.io/doc/overview) has a link to [https://www.npmjs.com/package/snaptest-cli](https://www.npmjs.com/package/snaptest-cli).  So you'll need to run:

`npm install -g snaptest-cli`

Let me know if that doesn't fix the issue.

(FYI, a few people have been asking for me to run the tests for them in the cloud for scheduling and monitoring services, so that'll be coming in a while.  I highly encourage getting real generation going tho because you own the code, so you're on the right track.)

**Comment by VR-Architect** [comment]
I deleted the snaptest-harness folder. Then ran the snaptest-cli install successfully. Then re-ran the folder code generator. Then got the error about the missing folder (which is not there). BTW, can you add a link to the snaptest-cli on this webpage to help newbies? It is underlined like a link, but no actual link.

https://www.snaptest.io/doc/getting-started

```
c:\OPT\Tests\snaptest-harness>npm test

> snaptest-harness@1.0.0 test c:\OPT\Tests\snaptest-harness
> nightwatch snaptests/tests

There was an error while starting the test runner:

Error: ENOENT: no such file or directory, stat 'c:\OPT\Tests\snaptest-harness\sn
aptests\tests'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.singleSourceFile (c:\OPT\Tests\snaptest-harness\node_modules\night
watch\lib\runner\cli\clirunner.js:193:86)
    at Object.parallelModeWorkers (c:\OPT\Tests\snaptest-harness\node_modules\ni
ghtwatch\lib\runner\cli\clirunner.js:717:44)
    at Object.parseTestSettings (c:\OPT\Tests\snaptest-harness\node_modules\nigh
twatch\lib\runner\cli\clirunner.js:532:14)
    at Object.setup (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch\lib\r
unner\cli\clirunner.js:49:8)
    at Object.exports.runner (c:\OPT\Tests\snaptest-harness\node_modules\nightwa
tch\lib\index.js:551:17)
    at c:\OPT\Tests\snaptest-harness\node_modules\nightwatch\bin\runner.js:10:16

    at Object.exports.cli (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch
\lib\index.js:545:5)
    at Object.<anonymous> (c:\OPT\Tests\snaptest-harness\node_modules\nightwatch
\bin\runner.js:8:14)

npm ERR! Test failed.  See above for more details.

c:\OPT\Tests\snaptest-harness>git clone https://github.com/ozymandias547/snaptes
t-harness.git && cd snaptest-harness && npm install && snaptest -f rJ22Dn-X- -r
nightwatch -s flat -t Fs5lrZMNZ5wgvDmFyMdvQaZgQ60RI6iEdwWFTd
Cloning into 'snaptest-harness'...
remote: Counting objects: 104, done.
Receiving objects:  44% (46remote: Total 104 (delta 0), reused 0 (delta 0), pack
Receiving objec
Receiving objects: 100% (104/104), 17.77 MiB | 2.48 MiB/s, done.
Resolving deltas: 100% (50/50), done.
npm WARN snaptest-harness@1.0.0 No repository field.

added 109 packages in 21.701s
'snaptest' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by VR-Architect** [comment]
Note the object count for the downloads does not appear to be complete when running the command. Says 48 out of 104 downloaded. Is this normal?

```
c:\OPT\Tests>git clone https://github.com/ozymandias547/snaptest-harness.git &&
cd snaptest-harness && npm install && snaptest -f xxxx -X- -r nightwatch -s fla
t -t xxxxxx
Cloning into 'snaptest-harness'...
remote: Counting objects: 104, done.
remote: Total 104 (delta 0), reused 0 (delta 0), pack-reused 104Receiving object
Receiving objects:  46% (48/104), 17.67 M
Receiving objects: 100% (104/104), 17.77 MiB | 5.02 MiB/s, done.
Resolving deltas: 100% (50/50), done.
npm WARN snaptest-harness@1.0.0 No repository field.

added 109 packages in 12.527s
'snaptest' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by VR-Architect** [comment]
I figured out the issue. I was running the commands from a CMD command line and not a NodeJS command line. Once I ran from NodeJS, the code downloaded (still 48/104 files though) and SnapTest generated the missing folder. 

Now I have another issue, but that is if another issue ticket.

**Comment by ozymandias547** [comment]
@VR-Architect Added the link - thanks.  Was doing src= insead of href= XD
