### ISSUE TITLE
Error - Java version?

### ISSUE THREAD

**Issue by VR-Architect** [ozymandias547/snaptest#21]
Is there minimium Java version required to run the tests from npm? I received this error. I am using Java v 1.6.0_25-b06 due to corporate limitations.

```
C:\OPT\Tests\snaptest-harness>npm test

> snaptest-harness@1.0.0 test C:\OPT\Tests\snaptest-harness
> nightwatch snaptests/tests

Starting selenium server in parallel mode... There was an error while starting t
he Selenium server:

java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3
: Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.openqa.grid.selenium.GridLauncherV3. Program
will exit.
Exception in thread "main"
npm ERR! Test failed.  See above for more details.

C:\OPT\Tests\snaptest-harness>java -version
java version "1.6.0_25"
Java(TM) SE Runtime Environment (build 1.6.0_25-b06)
Java HotSpot(TM) Client VM (build 20.0-b11, mixed mode)

C:\OPT\Tests\snaptest-harness>
```

**Comment by ozymandias547** [comment]
Looks like this issue: [https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0](https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0)

**Comment by VR-Architect** [comment]
So it looks like npm Test requires Java 8. So I upgrade and all worked great!

Please consider adding Java 8 to the requirements list in the docs and Get Started page. 
Thanks for the help

**Comment by ozymandias547** [comment]
Will do, thanks for getting that info for us :D
